compile:
	mkdir -p classes
	javac src/Arista.java -d classes
	javac src/Punto.java -d classes
	javac src/DisjSets.java -d classes
	javac -cp classes src/Segmento.java -d classes
	javac -cp classes src/Principal.java -d classes
run:
	java -cp ./classes Principal
clean:
	rm -r classes
